name: Node CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  ci:
    name: Continuous Integration Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci # install all dependencies
      - run: npm test # runs tests