name: Node CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  ci:
    name: Continuous Integration Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci # install all dependencies
      - run: npm test # runs tests
      - run: npm run compile-tsc # compiles all typescript files to javascript
      - run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev # install dependencies for node-canvas
      - run: npm run build-win # build project